HAFSA HAFEEZ SIDDIQUI (02-136212-026)

TEXT NORMALIZATION & DATA CLEANING

In [65]:
#importing libraries
import pandas as pd
import os
import string
import nltk
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer, WordNetLemmatizer
from nltk.tokenize import word_tokenize
import re

In [66]:
#reading the dataset
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [67]:
data_dir = '/content/drive/MyDrive/Airline_review.csv'
df = pd.read_csv(data_dir)

In [68]:
df.head()

,Unnamed: 0,Airline Name,Overall_Rating,Review_Title,Review Date,Verified,Review,Aircraft,Type Of Traveller,Seat Type,Route,Date Flown,Seat Comfort,Cabin Staff Service,Food & Beverages,Ground Service,Inflight Entertainment,Wifi & Connectivity,Value For Money,Recommended
0,0,AB Aviation,9,"""pretty decent airline""",11th November 2019,True,Moroni to Moheli. Turned out to be a pretty ...,NaN,Solo Leisure,Economy Class,Moroni to Moheli,Nov-19,4.0,5.0,4.0,4.0,NaN,NaN,3.0,yes
1,1,AB Aviation,1,"""Not a good airline""",25th June 2019,True,Moroni to Anjouan. It is a very small airline...,E120,Solo Leisure,Economy Class,Moroni to Anjouan,Jun-19,2.0,2.0,1.0,1.0,NaN,NaN,2.0,no
2,2,AB Aviation,1,"""flight was fortunately short""",25th June 2019,True,Anjouan to Dzaoudzi. A very small airline an...,Embraer E120,Solo Leisure,Economy Class,Anjouan to Dzaoudzi,Jun-19,2.0,1.0,1.0,1.0,NaN,NaN,2.0,no
3,3,Adria Airways,1,"""I will never fly again with Adria""",28th September 2019,False,Please do a favor yourself and do not fly wi...,NaN,Solo Leisure,Economy Class,Frankfurt to Pristina,Sep-19,1.0,1.0,NaN,1.0,NaN,NaN,1.0,no
4,4,Adria Airways,1,"""it ruined our last days of holidays""",24th September 2019,True,Do not book a flight with this airline! My fr...,NaN,Couple Leisure,Economy Class,Sofia to Amsterdam via Ljubljana,Sep-19,1.0,1.0,1.0,1.0,1.0,1.0,1.0,no

In [69]:
print(df.shape)

(23171, 20)

In [70]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23171 entries, 0 to 23170
Data columns (total 20 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Unnamed: 0              23171 non-null  int64
 1   Airline Name            23171 non-null  object
 2   Overall_Rating          23171 non-null  object
 3   Review_Title            23171 non-null  object
 4   Review Date             23171 non-null  object
 5   Verified                23171 non-null  bool
 6   Review                  23171 non-null  object
 7   Aircraft                7129 non-null   object
 8   Type Of Traveller       19433 non-null  object
 9   Seat Type               22075 non-null  object
 10  Route                   19343 non-null  object
 11  Date Flown              19417 non-null  object
 12  Seat Comfort            19016 non-null  float64
 13  Cabin Staff Service     18911 non-null  float64
 14  Food & Beverages        14500 non-null  float64
 15  Ground Service          18378 non-null  float64
 16  Inflight Entertainment  10829 non-null  float64
 17  Wifi & Connectivity     5920 non-null   float64
 18  Value For Money         22105 non-null  float64
 19  Recommended             23171 non-null  object
dtypes: bool(1), float64(7), int64(1), object(11)
memory usage: 3.4+ MB

REMOVAL OF PUNCTUATION MARKS:

Punctuation marks such as commas, periods, exclamation marks, and question marks serve grammatical purposes but
often do not contribute to the semantic meaning of text in NLP tasks. Removing punctuation marks helps in standardizing text and reducing noise.

1.   the string.punctuation constant from the string module is used to define a string containing all punctuation marks. This string includes characters such as "!", ".", ",", "?", etc.
2.   '[{}]'.format(punctuation) constructs a regular expression pattern to match any punctuation mark contained in the punctuation string.
3.    str.replace() then replaces any occurrence of punctuation marks in the specified column with an empty string, effectively removing them from the text.

In [71]:
# Define the punctuation marks to be removed
punctuation = string.punctuation

# Remove punctuation
df["Review_Title"] = df["Review_Title"].str.replace('[{}]'.format(punctuation), '')
df["Review"] = df["Review"].str.replace('[{}]'.format(punctuation), '')
df["Seat Type"] = df["Seat Type"].str.replace('[{}]'.format(punctuation), '')
df["Route"] = df["Route"].str.replace('[{}]'.format(punctuation), '')
df["Airline Name"] = df["Airline Name"].str.replace('[{}]'.format(punctuation), '')
df["Type Of Traveller"] = df["Type Of Traveller"].str.replace('[{}]'.format(punctuation), '')

<ipython-input-71-535b9746a735>:5: FutureWarning: The default value of regex will change from True to False in a future version.
  df["Review_Title"] = df["Review_Title"].str.replace('[{}]'.format(punctuation), '')
<ipython-input-71-535b9746a735>:6: FutureWarning: The default value of regex will change from True to False in a future version.
  df["Review"] = df["Review"].str.replace('[{}]'.format(punctuation), '')
<ipython-input-71-535b9746a735>:7: FutureWarning: The default value of regex will change from True to False in a future version.
  df["Seat Type"] = df["Seat Type"].str.replace('[{}]'.format(punctuation), '')
<ipython-input-71-535b9746a735>:8: FutureWarning: The default value of regex will change from True to False in a future version.
  df["Route"] = df["Route"].str.replace('[{}]'.format(punctuation), '')
<ipython-input-71-535b9746a735>:9: FutureWarning: The default value of regex will change from True to False in a future version.
  df["Airline Name"] = df["Airline Name"].str.replace('[{}]'.format(punctuation), '')
<ipython-input-71-535b9746a735>:10: FutureWarning: The default value of regex will change from True to False in a future version.
  df["Type Of Traveller"] = df["Type Of Traveller"].str.replace('[{}]'.format(punctuation), '')

CONVERTING TO LOWERCASE:

By converting all letters to lowercase, the vocabulary size is effectively reduced, as the same word in different cases is treated as a single token.

1.   str.lower() converts all letters in the text to lowercase, leaving any non-alphabetic characters unchanged.
2.   Each column's text data is transformed, ensuring that variations in letter case are normalized across all columns.

In [72]:
# Lowercase all text in the "text" column
df["Review_Title"] = df["Review_Title"].str.lower()
df["Review"] = df["Review"].str.lower()
df["Seat Type"] = df["Seat Type"].str.lower()
df["Route"] = df["Route"].str.lower()
df["Airline Name"] = df["Airline Name"].str.lower()
df["Type Of Traveller"] = df["Type Of Traveller"].str.lower()

TOKENIZATION:

Tokenization is a fundamental step in natural language processing (NLP) that involves breaking down text into smaller units, typically words or subwords.
1.  word_tokenize() is a function from the NLTK (Natural Language Toolkit) library that tokenizes text into individual words or tokens.
2.   By using apply(), the tokenization function is applied element-wise to each text entry in the specified columns, resulting in a list of tokens for each entry.

In [73]:
# Download for tokenization, stemming & lemmatization
nltk.download('punkt')
nltk.download('wordnet')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

In [74]:
# Tokenize two specific columns
df["Review_Title"] = df["Review_Title"].apply(word_tokenize)
df["Review"] = df["Review"].apply(word_tokenize)

REMOVAL OF NUMERIC NUMBERS:

Removing numeric characters is a common preprocessing step in NLP to eliminate numerical noise from textual data.
1.   Function Definition: remove_numeric_chars() is a Python function that takes a string text as input.
2.   List Comprehension: Within the function, a list comprehension is used to iterate over each character in the input text. For each character, it checks whether it is a digit using char.isdigit().
3.   Character Removal: If the character is not a digit, it is included in the resulting list. Otherwise, it is skipped.
4. Joining Characters: Finally, ''.join() is used to concatenate the characters in the resulting list back into a single string, effectively removing all numeric characters.

In [75]:
# Define a function to remove numeric characters
def remove_numeric_chars(text):
  return ''.join([char for char in text if not char.isdigit()])

df["Review_Title"] = df["Review_Title"].apply(remove_numeric_chars)
df["Review"] = df["Review"].apply(remove_numeric_chars)

REMOVAL OF STOPWORDS:

Stopwords are common words in a language that often do not carry significant meaning and are typically removed during text preprocessing in NLP tasks.

1. Stopwords Loading: The code first loads a list of English stopwords using the stopwords.words('english') function from the NLTK library. This list contains common English stopwords such as "the", "is", "and", etc.
2. Splitting and Filtering: Within the lambda function, each text entry in the column is split into individual words using x.split(). Then, a list comprehension is used to iterate over each word and retain only those words that are not present in the stop_words list.
3. Joining Words: The remaining words are joined back into a single string using ' '.join()

In [76]:
# Download the stopwords list
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [79]:
# Load the stopwords
stop_words = stopwords.words('english')

# Remove stop words
df["Review_Title"] = df["Review_Title"].apply(lambda x: ' '.join([word for word in x.split() if word not in stop_words]))
df["Review"] = df["Review"].apply(lambda x: ' '.join([word for word in x.split() if word not in stop_words]))

STEMMING & LEMMATIZATION:

Stemming and lemmatization are common text normalization techniques in natural language processing (NLP) that aim to reduce words to their base or root forms.

1. Word Tokenization: The text in each column is split into individual words using x.split().
2. Stemming Operation: For each word, stemming is applied using the stem() method of the stemming object (stemmer), which reduces the word to its base form.
3. Joining Words: The stemmed words are then joined back into a single string using ' '.join().

In [80]:
# Initialize the stemmer and lemmatizer
stemmer = PorterStemmer()
lemmatizer = WordNetLemmatizer()

# Stem the words
df["Review_Title"] = df["Review_Title"].astype(str)
df["Review_Title"] = df["Review_Title"].apply(lambda x: ' '.join([stemmer.stem(word) for word in x.split()]))
df["Review"] = df["Review"].astype(str)
df["Review"] = df["Review"].apply(lambda x: ' '.join([stemmer.stem(word) for word in x.split()]))

# Lemmatize the words
df["Review_Title"] = df["Review_Title"].apply(lambda x: ' '.join([lemmatizer.lemmatize(word) for word in x.split()]))
df["Review"] = df["Review"].apply(lambda x: ' '.join([lemmatizer.lemmatize(word) for word in x.split()]))

In [81]:
# Display the first few rows of the DataFrame
df.head(20)

,Unnamed: 0,Airline Name,Overall_Rating,Review_Title,Review Date,Verified,Review,Aircraft,Type Of Traveller,Seat Type,Route,Date Flown,Seat Comfort,Cabin Staff Service,Food & Beverages,Ground Service,Inflight Entertainment,Wifi & Connectivity,Value For Money,Recommended
0,0,ab aviation,9,prettydecentairlin,11th November 2019,True,moronitomoheliturnedouttobeaprettydecentairlin...,NaN,solo leisure,economy class,moroni to moheli,Nov-19,4.0,5.0,4.0,4.0,NaN,NaN,3.0,yes
1,1,ab aviation,1,notagoodairlin,25th June 2019,True,moronitoanjouanitisaverysmallairlinemyticketad...,E120,solo leisure,economy class,moroni to anjouan,Jun-19,2.0,2.0,1.0,1.0,NaN,NaN,2.0,no
2,2,ab aviation,1,flightwasfortunatelyshort,25th June 2019,True,anjouantodzaoudziaverysmallairlineandtheonlyai...,Embraer E120,solo leisure,economy class,anjouan to dzaoudzi,Jun-19,2.0,1.0,1.0,1.0,NaN,NaN,2.0,no
3,3,adria airways,1,iwillneverflyagainwithadria,28th September 2019,False,pleasedoafavoryourselfanddonotflywithadriaonth...,NaN,solo leisure,economy class,frankfurt to pristina,Sep-19,1.0,1.0,NaN,1.0,NaN,NaN,1.0,no
4,4,adria airways,1,itruinedourlastdaysofholiday,24th September 2019,True,donotbookaflightwiththisairlinemyfriendandisho...,NaN,couple leisure,economy class,sofia to amsterdam via ljubljana,Sep-19,1.0,1.0,1.0,1.0,1.0,1.0,1.0,no
5,5,adria airways,1,hadverybadexperi,17th September 2019,True,hadverybadexperiencewithreroutedandcancelledfl...,CR 900,couple leisure,economy class,sarajevo to ljubljana,Sep-19,1.0,1.0,1.0,1.0,1.0,1.0,1.0,no
6,6,adria airways,1,worsethanthebudgetairlin,6th September 2019,False,ljubljanatozürichfirstlyljubljanaairportisterr...,NaN,business,economy class,ljubljana to zürich,Sep-19,1.0,1.0,1.0,1.0,NaN,NaN,1.0,no
7,7,adria airways,1,bookanothercompani,24th August 2019,False,firstofalliamnotcomplainingaboutaspecificfligh...,Bombardier CRJ,solo leisure,economy class,timisoara to munich,Aug-19,1.0,1.0,1.0,1.0,1.0,1.0,1.0,no
8,8,adria airways,1,combinedtwoflight,6th August 2019,True,worstairlineevertheycombinedtwoflightstosaveco...,NaN,solo leisure,economy class,pristina to zürich via ljubliana,Aug-19,1.0,2.0,1.0,1.0,1.0,1.0,1.0,no
9,9,adria airways,8,thecrewwasnic,12th October 2018,True,ljubljanatomunichthehomebaseairportofadriaairw...,NaN,family leisure,economy class,ljubljana to munich,Oct-18,4.0,4.0,3.0,5.0,NaN,NaN,5.0,yes
10,10,adria airways,1,verybadexperienceoveral,5th October 2018,False,zurichtoljubljanaverypoorcustomerserviceflight...,NaN,business,economy class,zurich to ljubljana,Oct-18,2.0,1.0,NaN,1.0,1.0,1.0,1.0,no
11,11,adria airways,1,badcustomerservic,29th July 2018,True,viennatosofiatheflightwasdelayedbyhoursthecabi...,NaN,family leisure,economy class,vienna to sofia,Jul-18,4.0,1.0,1.0,4.0,NaN,NaN,1.0,no
12,12,adria airways,2,overallverypoor,19th July 2018,True,weweretravelingfromparistoskopjeonmay4thvialju...,NaN,solo leisure,economy class,paris to skopje via ljubljana,May-18,3.0,3.0,NaN,3.0,NaN,NaN,2.0,no
13,13,adria airways,2,wouldnotflyagain,30th June 2018,True,ljubljanatomunichadriascheckinsystemisobviousl...,NaN,business,economy class,ljubljana to munich,Jun-18,1.0,2.0,2.0,2.0,NaN,NaN,1.0,no
14,14,adria airways,3,veryunpleasantexperi,24th June 2018,True,averyunpleasantexperienceformyfamilyweboughttw...,A319,couple leisure,economy class,ljubljana to prague,Jun-18,3.0,3.0,NaN,1.0,NaN,NaN,1.0,no
15,15,adria airways,1,flightwasverycomfort,4th May 2018,True,frankfurttoljubljanaflightwasverycomfortablepr...,NaN,business,economy class,frankfurt to ljubljana,Apr-18,5.0,5.0,5.0,5.0,NaN,NaN,5.0,yes
16,16,adria airways,1,delayedformorethanhour,11th March 2018,True,ljubljanatofrankfurtflightdelayedformorethanho...,NaN,solo leisure,economy class,ljubljana to frankfurt,Mar-18,2.0,1.0,1.0,1.0,1.0,1.0,1.0,no
17,17,adria airways,3,shouldbeashamedoftheiroper,5th December 2017,True,ljubljanatoviennaoveralltheflightservicesofadr...,ATR-72,solo leisure,economy class,ljubljana to vienna,Sep-17,2.0,4.0,1.0,1.0,NaN,NaN,3.0,no
18,18,adria airways,9,twoniceshortflight,20th November 2017,True,twoniceshortflightsfromljubljanatosarajevoandb...,CRJ700 / ATR72,business,economy class,ljubljana to sarajevo,Nov-17,5.0,5.0,3.0,5.0,NaN,NaN,3.0,yes
19,19,adria airways,2,extremelybadservic,27th October 2017,False,wewerepeoplecominginwithashortconnectiontozuri...,NaN,couple leisure,economy class,zurich to ljubjana,Oct-17,3.0,3.0,NaN,1.0,NaN,NaN,1.0,no